module.exports = {
		CATEGORY: {
				"UPDATED": "CATEGORY_UPDATED",
				"CANCELLED": "CATEGORY_CANCELLED",
				"DELETED": "CATEGORY_DELETED"
		},
		PRODUCT: {
				"UPDATED": "PRODUCT_UPDATED",
				"CANCELLED": "PRODUCT_CANCELLED",
				"DELETED": "PRODUCT_DELETED"
		},
		ORDER: {
				"UPDATED": "ORDER_UPDATED",
				"CANCELLED": "ORDER_CANCELLED",
				"DELETED": "ORDER_DELETED"
		}
};
